#spring
spring:
  freemarker:
    #默认后缀为.ftl  修改为.html
    suffix: .html
  profiles:
    active: dev
  aop:
    proxy-target-class: true

#mmybatis-plus   版本2和3用法有差别 此处为3
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

##logging
#logging:
#  level: warn
#beetl
beetlsql:
  enabled: false
beetl:
  enabled: true
#,默认为true，即自动检查模板变化
beetl-beetlsql:
  dev: true